server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    include: oauth2, local

  jpa:
    hibernate:
      ddl-auto: create-drop #create update none
      show-sql: true
